#!/bin/bash



./tag-header stdio.h
./geninc stdio.tags  ../inc/stdio.inc libctypes.txt stdio _LIBC +stdio.pre


	
./tag-header stdlib.h
./geninc stdlib.tags  ../inc/stdlib.inc libctypes.txt stdlib _LIBC



