#!/bin/bash
#source config


./tag-header stdio.h
./geninc stdio.tags  ../inc/stdio.inc libctypes.txt stdio _LIBC +stdio.pre


	
./tag-header stdlib.h
./geninc stdlib.tags  ../inc/stdlib.inc libctypes.txt stdlib _LIBC


./tag-header stdlib.h
./geninc stdlib.tags  ../inc/stdlib.inc libctypes.txt stdlib _LIBC




./tag-header GLFW/callbacks.h
./geninc callbacks.tags  callbacks.inc glfw3types.txt x x  pglfw
#extract callback types to make types;
cp glfw3types.txt  glfw3types2.txt
cat callbacks.inc  | grep sys | awk -F\"  '{print $4 ";" $1}' >> glfw3types2.txt


./tag-header GLFW/glfw3.h
./geninc glfw3.tags  ../inc/glfw3.inc glfw3types2.txt glfw libglfw.so.3 pglfw




./tag-header GL/glcorearb.h
./geninc glcorearb.tags  ../inc/glcorearb.inc gltypes.txt gl libGL.so.1 pgl

./tag-header GL/gl.h
./geninc gl.tags  ../inc/glold.inc gltypes.txt glold libGL.so.1 pgl

./tag-header zgl.h
./geninc zgl.tags  ../inc/zgl.inc zgltypes.txt zgl _INTERNAL pzgl azgl.post

./tag-header fluidsynth.h
./geninc fluidsynth.tags  ../inc/fluidsynth.inc fluidsynthtypes.txt fsynth libfluidsynth.so pfluid  # afluidsynth.post


